### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [ArMoraer/QGISMergeLines#1]
.pyc etc.

**Comment by ArMoraer** [comment]
Ok, I removed .pyc files, "help" and "script" folders, and a few other files.

**Comment by pcav** [comment]
Thanks. Please let me know when you upload a new version.

**Comment by ArMoraer** [comment]
All right; I'm not familiar with the publishing process of QGIS plugins. The current version (0.1.1) should not be modified in the near future, so you can consider it "stable". Thanks for the follow-up.
