### ISSUE TITLE
Please explain the usefulness

### ISSUE THREAD

**Issue by pcav** [ArMoraer/QGISMergeLines#2]
There are other plugins apparently quite similar. Please explain in the About the reasons to use this rather than others.

**Comment by ArMoraer** [comment]
I have identified 3 plugins that seem to serve a similar purpose : "Join lines", "Join multiples lines" and "Multiline join".

The main difference between the first two plugins and MergeLines is that MergeLines _automatically_ merges features in a line layer, which proves useful when dealing with a large number of lines. In "Join lines" and "Join multiples lines", features have to be manually selected.

"Multiline join" deals with polylines. As far as I unterstand it, it simplifies polylines by merging parts a polyline together. MergeLines deals with networks of simple lines, and merges these lines according to various rules (which should become more complex in the near future).

I will report this in the README file.

**Comment by pcav** [comment]
Thanks. Please add it also to the About, so, users will see it before installing.
Please also consider merging your work with that of others: one plugin with 3 developers is far better than 3 plugins with one each, even considering the extra effort to coordinate them.
